// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

export interface OperationDoc {
  operationId: string;
  resource: string;
  action: string;
  method: string;
  path: string;
  summary: string;
  description: string;
  parameters: Array<{
    name: string;
    in: string;
    required: boolean;
    description: string;
  }>;
  requestBody: {
    required: boolean;
    schema: string;
  } | null;
  response: {
    schema: string;
    unwrapsTo: string | null;
  } | null;
  pagination: string;
  idempotent: boolean;
}

export const operationDocs = [
  {
    "operationId": "client.health",
    "resource": "client",
    "action": "health",
    "method": "GET",
    "path": "/v1/health",
    "summary": "Health probe",
    "description": "Lightweight liveness probe. Returns a 200 with a fixed message when the API process is up. Does not verify downstream dependencies (database, storage, workers) — use the internal status endpoints for those.",
    "parameters": [],
    "requestBody": null,
    "response": {
      "schema": "WrappedGenericMessageResponse",
      "unwrapsTo": "GenericMessageResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "collections.create",
    "resource": "collections",
    "action": "create",
    "method": "POST",
    "path": "/v1/collections",
    "summary": "Create a new collection",
    "description": "Create a new collection and automatically add the creating user\nto it.\n\nThis endpoint allows authenticated users to create a new collection\nwith a specified name and optional description. The user creating\nthe collection is automatically added as a member.",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "CreateCollectionRequest"
    },
    "response": {
      "schema": "WrappedCollectionResponse",
      "unwrapsTo": "CollectionResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "collections.delete",
    "resource": "collections",
    "action": "delete",
    "method": "DELETE",
    "path": "/v1/collections/{id}",
    "summary": "Delete collection",
    "description": "Delete an existing collection.\n\nThis endpoint allows deletion of a collection identified by its\nUUID. The user must have appropriate permissions to delete the\ncollection. Deleting a collection removes all associations but does\nnot delete the engrams within it.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The unique identifier of the collection to delete"
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedGenericBooleanResponse",
      "unwrapsTo": "GenericBooleanResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "collections.list",
    "resource": "collections",
    "action": "list",
    "method": "GET",
    "path": "/v1/collections",
    "summary": "List collections",
    "description": "Returns a cursor-paginated list of collections the authenticated\nuser has access to.\n\nResults can be filtered by providing specific collection IDs.\nRegular users will only see collections they own or have access to.\nSuperusers can see all collections.\n\nThe collections are returned in order of last modification, with\nmost recent first.",
    "parameters": [
      {
        "name": "ids",
        "in": "query",
        "required": false,
        "description": "A list of collection IDs to retrieve. If not provided, all collections will be returned."
      },
      {
        "name": "name",
        "in": "query",
        "required": false,
        "description": "Filter collections by name (case-insensitive exact match)."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "description": "Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "description": "Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100."
      },
      {
        "name": "owner_only",
        "in": "query",
        "required": false,
        "description": "If true, only returns collections owned by the user, not all accessible collections."
      },
      {
        "name": "workspace_id",
        "in": "query",
        "required": false,
        "description": "Filter by workspace ID. Pass a UUID to scope to a workspace, or omit for all."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "PaginatedCollectionResponse",
      "unwrapsTo": null
    },
    "pagination": "cursor",
    "idempotent": true
  },
  {
    "operationId": "collections.retrieve",
    "resource": "collections",
    "action": "retrieve",
    "method": "GET",
    "path": "/v1/collections/{id}",
    "summary": "Get collection details",
    "description": "Get details of a specific collection.\n\nThis endpoint retrieves detailed information about a single\ncollection identified by its UUID. The user must have access to the\ncollection to view its details.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The unique identifier of the collection"
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedCollectionResponse",
      "unwrapsTo": "CollectionResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "collections.retrieveByName",
    "resource": "collections",
    "action": "retrieveByName",
    "method": "GET",
    "path": "/v1/collections/name/{collection_name}",
    "summary": "Get a collection by name",
    "description": "Retrieve a collection by its (owner_id, name) combination.\n\nThe authenticated user can only fetch collections they own, or, if\nsuperuser, from anyone.",
    "parameters": [
      {
        "name": "collection_name",
        "in": "path",
        "required": true,
        "description": "The name of the collection"
      },
      {
        "name": "owner_id",
        "in": "query",
        "required": false,
        "description": "(Superuser only) Specify the owner_id to retrieve a collection by name"
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedCollectionResponse",
      "unwrapsTo": "CollectionResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "collections.update",
    "resource": "collections",
    "action": "update",
    "method": "POST",
    "path": "/v1/collections/{id}",
    "summary": "Update collection",
    "description": "Update an existing collection's configuration.\n\nThis endpoint allows updating the name, description, and access settings of an\nexisting collection. The user must have appropriate permissions to\nmodify the collection.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The unique identifier of the collection to update"
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "UpdateCollectionRequest"
    },
    "response": {
      "schema": "WrappedCollectionResponse",
      "unwrapsTo": "CollectionResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "connectors.connect",
    "resource": "connectors",
    "action": "connect",
    "method": "POST",
    "path": "/v1/connectors/{provider}/connect",
    "summary": "Start OAuth connection flow",
    "description": "Start the OAuth connection flow for the given external provider. Returns the authorization URL the user should visit to grant Nebula access. After consent the provider redirects back to Nebula and the connection becomes active.",
    "parameters": [
      {
        "name": "provider",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "ConnectRequest"
    },
    "response": {
      "schema": "WrappedConnectorConnectResponse",
      "unwrapsTo": "ConnectorConnectResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "connectors.disconnect",
    "resource": "connectors",
    "action": "disconnect",
    "method": "DELETE",
    "path": "/v1/connectors/{connection_id}",
    "summary": "Disconnect an external data source",
    "description": "Disconnect the named connection, revoking the stored OAuth credentials and stopping future syncs. Optionally pass `delete_memories=true` to also remove every memory this connection had ingested.",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "description": ""
      },
      {
        "name": "delete_memories",
        "in": "query",
        "required": false,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedConnectorDisconnectResponse",
      "unwrapsTo": "ConnectorDisconnectResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "connectors.list",
    "resource": "connectors",
    "action": "list",
    "method": "GET",
    "path": "/v1/connectors",
    "summary": "List active connections for a collection",
    "description": "Return every connector connection associated with the given collection, with encrypted credentials redacted. Useful for showing the user which third-party data sources are wired up to a collection.",
    "parameters": [
      {
        "name": "collection_id",
        "in": "query",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedListOfConnectorConnectionResponse",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "connectors.listProviders",
    "resource": "connectors",
    "action": "listProviders",
    "method": "GET",
    "path": "/v1/connectors/providers",
    "summary": "List available connector providers",
    "description": "Return the set of connector provider identifiers (e.g. `google_drive`, `slack`) that this Nebula instance is configured to expose. Pass one of these to `POST /connectors/{provider}/connect` to start an OAuth flow.",
    "parameters": [],
    "requestBody": null,
    "response": {
      "schema": "WrappedListOfStr",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "connectors.retrieve",
    "resource": "connectors",
    "action": "retrieve",
    "method": "GET",
    "path": "/v1/connectors/{connection_id}",
    "summary": "Get a single connection by ID",
    "description": "Fetch a single connector connection by its UUID. Returns the connection metadata plus whether the underlying subscription is active. Encrypted credentials are never returned to clients.",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedConnectorConnectionResponse",
      "unwrapsTo": "ConnectorConnectionResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "connectors.sync",
    "resource": "connectors",
    "action": "sync",
    "method": "POST",
    "path": "/v1/connectors/{connection_id}/sync",
    "summary": "Manually trigger a sync",
    "description": "Schedule an immediate sync for an active connection, bypassing the normal cadence. Returns 409 if a sync is already in progress and 400 if the connection isn't in the `active` state.",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedConnectorSyncResponse",
      "unwrapsTo": "ConnectorSyncResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "memories.append",
    "resource": "memories",
    "action": "append",
    "method": "POST",
    "path": "/v1/memories/{id}/append",
    "summary": "Append content to an engram",
    "description": "Append content to an existing engram.\n\n**For conversation engrams:**\n- Provide `messages` array with content, role, and optional metadata\n- Works like `/conversations/{id}/messages` endpoint\n\n**For document engrams:**\n- Provide either `raw_text` or `chunks` to append additional content\n- Content will be processed and added to the engram",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The unique identifier of the engram"
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "AppendMemoryRequest"
    },
    "response": {
      "schema": "inline",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.completeUpload",
    "resource": "memories",
    "action": "completeUpload",
    "method": "POST",
    "path": "/v1/memories/upload/{upload_session_id}/complete",
    "summary": "Complete multipart upload session",
    "description": "Finalize an upload session after every multipart upload part has been uploaded.",
    "parameters": [
      {
        "name": "upload_session_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "CompleteMultipartUploadRequest"
    },
    "response": {
      "schema": "WrappedCompleteMultipartUploadResponse",
      "unwrapsTo": "CompleteMultipartUploadResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.create",
    "resource": "memories",
    "action": "create",
    "method": "POST",
    "path": "/v1/memories",
    "summary": "Create a new memory (conversation or document)",
    "description": "Create a new memory (conversation or document) using clean JSON body.\n\n- Use `collection_id` (UUID)\n- `kind` is optional and inferred from payload shape:\n  - If `messages` present -> conversation\n  - Otherwise -> document\n- For conversations: provide `messages` array\n- For documents: provide `raw_text` or `chunks`\n- Use `snapshot` for device-memory mode (mutually exclusive with collection_id)",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "CreateMemoryRequest"
    },
    "response": {
      "schema": "MemoryCreateResponse",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.createUpload",
    "resource": "memories",
    "action": "createUpload",
    "method": "POST",
    "path": "/v1/memories/upload",
    "summary": "Create multipart upload session",
    "description": "Create a workspace-scoped multipart upload session.",
    "parameters": [
      {
        "name": "filename",
        "in": "query",
        "required": true,
        "description": "Original filename (e.g., 'image.jpg')"
      },
      {
        "name": "content_type",
        "in": "query",
        "required": true,
        "description": "MIME type (e.g., 'image/jpeg', 'application/pdf')"
      },
      {
        "name": "file_size",
        "in": "query",
        "required": true,
        "description": "Expected file size in bytes (max 100MB)"
      },
      {
        "name": "collection_id",
        "in": "query",
        "required": false,
        "description": "Optional target collection for workspace-scoped uploads."
      },
      {
        "name": "client_idempotency_key",
        "in": "query",
        "required": false,
        "description": "Optional client key for retrying upload-session creation."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedMultipartUploadSessionResponse",
      "unwrapsTo": "MultipartUploadSessionResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.delete",
    "resource": "memories",
    "action": "delete",
    "method": "DELETE",
    "path": "/v1/memories/{id}",
    "summary": "Delete an engram",
    "description": "Delete a specific engram with graph awareness. All chunks corresponding to the\nengram are deleted, and graph components (entities/relationships) are updated\nor deleted based on remaining chunk references from other engrams.\n\nThis method now properly handles graph components and maintains graph integrity\nfor search operations.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "Engram ID"
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedGenericBooleanResponse",
      "unwrapsTo": "GenericBooleanResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.deleteMany",
    "resource": "memories",
    "action": "deleteMany",
    "method": "POST",
    "path": "/v1/memories/delete",
    "summary": "Delete one or more engrams",
    "description": "Delete one or more engrams.\n\nThis endpoint efficiently handles both single and batch deletions.\nWhen multiple IDs are provided, it uses optimized batch operations.\n\nArgs:\n    ids: Either a single UUID or a list of UUIDs to delete\n\nReturns:\n    For single deletion: boolean success response\n    For batch deletion: detailed results with successful and failed deletions",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "DeleteMemoriesRequest"
    },
    "response": {
      "schema": "inline",
      "unwrapsTo": null
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.deleteUpload",
    "resource": "memories",
    "action": "deleteUpload",
    "method": "DELETE",
    "path": "/v1/memories/upload",
    "summary": "Delete a pending upload session",
    "description": "Delete a pending upload session and its staged object.",
    "parameters": [
      {
        "name": "upload_session_id",
        "in": "query",
        "required": true,
        "description": "Upload session ID returned by memories.createUpload."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedGenericMessageResponse",
      "unwrapsTo": "GenericMessageResponse"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "memories.list",
    "resource": "memories",
    "action": "list",
    "method": "GET",
    "path": "/v1/memories",
    "summary": "List engrams",
    "description": "Returns a cursor-paginated list of engrams the authenticated user\nhas access to.\n\nResults can be filtered by providing specific engram IDs or collection IDs.\nRegular users will only see engrams they own or have access to through\ncollections. Superusers can see all engrams.\n\nThe engrams are returned in order of creation time, most recent\nfirst. The response includes the engram's text field if available.",
    "parameters": [
      {
        "name": "ids",
        "in": "query",
        "required": false,
        "description": "A list of engram IDs to retrieve. If not provided, all engrams will be returned."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "description": "Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "description": "Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100."
      },
      {
        "name": "chunks_limit",
        "in": "query",
        "required": false,
        "description": "Maximum chunks to inline per engram. Defaults to all chunks for backwards compatibility; pass 0 to skip chunk hydration."
      },
      {
        "name": "owner_only",
        "in": "query",
        "required": false,
        "description": "If true, only returns engrams owned by the user, not all accessible engrams."
      },
      {
        "name": "collection_ids",
        "in": "query",
        "required": false,
        "description": "Optional list of collection IDs to filter engrams by. If provided, exactly one collection ID must be specified."
      },
      {
        "name": "metadata_filters",
        "in": "query",
        "required": false,
        "description": "JSON string for metadata filtering. Example: '{\"metadata.source\": {\"$eq\": \"playground\"}}'"
      },
      {
        "name": "min_applied_wal_seq",
        "in": "query",
        "required": false,
        "description": "Read-your-writes assertion: the WAL-tail overlay path waits for at least this seq to be applied before serving (or returns 503 Unavailable on timeout). REQUIRES exactly one collection_ids entry — without a collection scope the request returns 422 (the per-WAL-shard scalar applied_wal_seq is meaningless across collections). When the served shard has not been migrated to wal_compaction_enabled, the field is accepted but the served path is the legacy overlay (the assertion has no effect — the response's applied_wal_seq will be 0). Pass back the value the matching upload response surfaced."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "PaginatedListedEngram",
      "unwrapsTo": null
    },
    "pagination": "cursor",
    "idempotent": true
  },
  {
    "operationId": "memories.recallWorkflow",
    "resource": "memories",
    "action": "recallWorkflow",
    "method": "POST",
    "path": "/v1/memories/workflow/recall",
    "summary": "Recall workflow patterns by intent",
    "description": "Workflow-pattern recall over 5 intents.\n\n* ``cursor`` -- match the caller's anchor against pattern\n  canonical states, return ranked patterns + position.\n* ``predict`` -- like cursor but include the predicted next\n  trace from each pattern's canonical instance.\n* ``resume`` -- like cursor, biased toward longer patterns.\n* ``evidence`` -- expand a specific pattern via\n  ``hydrate_pattern``.\n* ``bootstrap`` -- top-K patterns by confidence with no anchor.",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "inline"
    },
    "response": {
      "schema": "WorkflowRecallResponse",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.retrieve",
    "resource": "memories",
    "action": "retrieve",
    "method": "GET",
    "path": "/v1/memories/{id}",
    "summary": "Retrieve an engram",
    "description": "Retrieves detailed information about a specific engram by its\nID.\n\nThis endpoint returns the engram's metadata, status, and system information. It does not\nreturn the engram's content - use the `/engrams/{id}/download` endpoint for that.\n\nUsers can only retrieve engrams they own or have access to through collections.\nSuperusers can retrieve any engram.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The ID of the engram to retrieve."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedEngram",
      "unwrapsTo": "Engram"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "memories.search",
    "resource": "memories",
    "action": "search",
    "method": "POST",
    "path": "/v1/memories/search",
    "summary": "Search memories",
    "description": "Perform a search query across your memories.\n\n**Standard mode** (collection_ids or readable-scope search): returns hierarchical MemoryRecall\nwith semantics, episodes, procedures, and sources.\n\n**Snapshot mode** (snapshot field): returns graph-search results with\n{entities, relationships} from stateless in-memory traversal.",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "MemorySearchRequest"
    },
    "response": {
      "schema": "inline",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.signUploadPart",
    "resource": "memories",
    "action": "signUploadPart",
    "method": "POST",
    "path": "/v1/memories/upload/{upload_session_id}/parts/{part_number}",
    "summary": "Create multipart upload part URL",
    "description": "Create a presigned URL for uploading one part of an existing memory upload session.",
    "parameters": [
      {
        "name": "upload_session_id",
        "in": "path",
        "required": true,
        "description": ""
      },
      {
        "name": "part_number",
        "in": "path",
        "required": true,
        "description": ""
      },
      {
        "name": "checksum_sha256",
        "in": "query",
        "required": true,
        "description": "Base64-encoded SHA-256 checksum for this part."
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedMultipartUploadPartResponse",
      "unwrapsTo": "MultipartUploadPartResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "memories.update",
    "resource": "memories",
    "action": "update",
    "method": "PATCH",
    "path": "/v1/memories/{id}",
    "summary": "Update a memory",
    "description": "Update memory-level properties including name, metadata, and collection associations.\n\nThis endpoint allows updating properties of an entire memory (document or conversation)\nwithout modifying its content:\n- **name**: Updates the authoritative engram title\n- **metadata**: Can replace or merge with existing metadata\n- **collection_ids**: Updates authoritative engram collection associations\n\nUsers can only update memories they own or have access to through collections.\nAt least one collection association must be maintained.\n\nIf collection_id is provided and the engram is shared across collections, a copy-on-write\nwill be performed to create a collection-specific copy before modification.",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "The unique identifier of the memory"
      },
      {
        "name": "collection_id",
        "in": "query",
        "required": false,
        "description": "Collection context for copy-on-write. If provided and engram is shared, creates a copy before modification."
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "UpdateMemoryRequest"
    },
    "response": {
      "schema": "WrappedEngram",
      "unwrapsTo": "Engram"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "snapshots.export",
    "resource": "snapshots",
    "action": "export",
    "method": "POST",
    "path": "/v1/device-memory/snapshot/export",
    "summary": "Export a collection snapshot",
    "description": "Export a collection's full graph state as a\nportable SnapshotEnvelope.",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "SnapshotExportRequest"
    },
    "response": {
      "schema": "WrappedSnapshotEnvelopeOrSnapshotObjectReference",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "snapshots.import",
    "resource": "snapshots",
    "action": "import",
    "method": "POST",
    "path": "/v1/device-memory/snapshot/import",
    "summary": "Import a snapshot into an ephemeral collection",
    "description": "Import a SnapshotEnvelope into an ephemeral\ncollection. Returns the ephemeral collection UUID.",
    "parameters": [],
    "requestBody": {
      "required": true,
      "schema": "SnapshotImportRequest"
    },
    "response": {
      "schema": "WrappedSnapshotImportResult",
      "unwrapsTo": "SnapshotImportResult"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "workspaces.createStorageTarget",
    "resource": "workspaces",
    "action": "createStorageTarget",
    "method": "POST",
    "path": "/v1/workspaces/{workspace_id}/storage-targets",
    "summary": "Create workspace storage target",
    "description": "Register a customer S3 bucket for hosted BYOC storage.",
    "parameters": [
      {
        "name": "workspace_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": {
      "required": true,
      "schema": "StorageTargetCreateRequest"
    },
    "response": {
      "schema": "WrappedStorageTargetResponse",
      "unwrapsTo": "StorageTargetResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "workspaces.disableStorageTarget",
    "resource": "workspaces",
    "action": "disableStorageTarget",
    "method": "DELETE",
    "path": "/v1/workspaces/{workspace_id}/storage-targets/{target_id}",
    "summary": "Disable workspace storage target",
    "description": "Disable a customer storage target for future collection binds.",
    "parameters": [
      {
        "name": "workspace_id",
        "in": "path",
        "required": true,
        "description": ""
      },
      {
        "name": "target_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedStorageTargetResponse",
      "unwrapsTo": "StorageTargetResponse"
    },
    "pagination": "none",
    "idempotent": false
  },
  {
    "operationId": "workspaces.listStorageTargets",
    "resource": "workspaces",
    "action": "listStorageTargets",
    "method": "GET",
    "path": "/v1/workspaces/{workspace_id}/storage-targets",
    "summary": "List workspace storage targets",
    "description": "List customer-owned object storage targets for a workspace.",
    "parameters": [
      {
        "name": "workspace_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedListOfStorageTargetResponse",
      "unwrapsTo": "inline"
    },
    "pagination": "none",
    "idempotent": true
  },
  {
    "operationId": "workspaces.validateStorageTarget",
    "resource": "workspaces",
    "action": "validateStorageTarget",
    "method": "POST",
    "path": "/v1/workspaces/{workspace_id}/storage-targets/{target_id}/validate",
    "summary": "Validate workspace storage target",
    "description": "Probe a customer storage target and mark it active on success.",
    "parameters": [
      {
        "name": "workspace_id",
        "in": "path",
        "required": true,
        "description": ""
      },
      {
        "name": "target_id",
        "in": "path",
        "required": true,
        "description": ""
      }
    ],
    "requestBody": null,
    "response": {
      "schema": "WrappedStorageTargetResponse",
      "unwrapsTo": "StorageTargetResponse"
    },
    "pagination": "none",
    "idempotent": false
  }
] satisfies OperationDoc[];
